name: CI

env:
  # because it takes a loooong time
  HOMEBREW_NO_AUTO_UPDATE: 1

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    strategy:
      # avoid macos builds (more expensive) if ubuntu builds fail
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          # builds on windows fail
          # https://github.com/bazelbuild/rules_docker/issues/1524
          # https://github.com/bazelbuild/rules_docker/issues/1438
          # - windows-latest
        bazel: [4.2.4, 5.4.1, 6.3.2]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    name: test-on-${{ matrix.os }}-with-bazel-${{ matrix.bazel }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: jwlawson/actions-setup-bazel@v1
        with:
          bazel-version: ${{ matrix.bazel }}
          github-api-token: ${{ secrets.READONLY_TOKEN }}
      - name: Mount bazel action cache
        uses: actions/cache@v2
        with:
          path: "~/.cache/bazel"
          key: bazel
      - name: Mount bazel repo cache
        uses: actions/cache@v2
        with:
          path: "~/.cache/bazel-repo"
          key: bazel-repo
      - name: Set Bazel Version ${{ matrix.bazel }}
        run: echo ${{ matrix.bazel }} > .bazelversion
      - name: Build
        shell: bash
        run: bazel --bazelrc=.github/workflows/ci.bazelrc --bazelrc=.bazelrc build ...
      - name: Test
        shell: bash
        run: bazel --bazelrc=.github/workflows/ci.bazelrc --bazelrc=.bazelrc test ...
